# Change these first
owner: kjappelbaum # Your GitHub organization or username
repo: cheminfo-status # Your GitHub repository name

# Add your sites here
sites:
  - name: c6h6
    url: https://www.c6h6.org/
  - name: eln.epfl.ch
    url: https://eln.epfl.ch
  - name: xrd.cheminfo.org
    url: https://xrd.cheminfo.org
  - name: crystal.cheminfo.org
    url: https://crystal.cheminfo.org/
  - name: chemcalc
    url: https://www.chemcalc.org/
  - name: ecoscale
    url: http://ecoscale.cheminfo.org/
  - name: polycalc
    url: https://www.polycalc.org/
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /cheminfo-status
  logoUrl: https://raw.githubusercontent.com/cheminfo/cheminfo.github.io/main/docs/assets/images/logo.svg
  name: cheminfo status
  introTitle: "**cheminfo** is an open-source effort that creates building blocks for the capture, processing, and analysis of (chemical) data."
  introMessage: This status page reports the uptime for the services we provide and tracks any on-going incidents.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
